### ISSUE TITLE
なんか画像表示されなくね

### ISSUE THREAD

**Issue by Chipsnet** [Chipsnet/ka3de.work#18]

**Comment by Rlettuce05** [comment]
nuxt-imgで開いてる画像が表示されてないっぽい？

**Comment by Chipsnet** [comment]
ファ～
仕事終わったら確認するか・・・

**Comment by Chipsnet** [comment]
プレビューだと正しく表示されてるから単純にキャッシュの問題かもしれない
https://98a6a1a5.ka3de-work.pages.dev/
